version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3

    groups:
      react-runtime:
        patterns:
          - react
          - react-dom

      storybook:
        patterns:
          - storybook
          - "@storybook/*"
