import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/theme/theme-provider';

import '@/styles/layers.css';
import '@/styles//globals.css';
import '@/styles/reset.css';
import '@/styles/tokens.css';
import '@/styles/a11y.css';
import '@/styles/themes.css';
import '@/styles/globals.css';
import { NoiseFilter } from '@/components/effects/noise-filter';
import { geistMono, geistSans } from '@/styles/fonts';
import SkipLink from '../components/a11y/skip-link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <ThemeProvider>
          <NoiseFilter />
          <SkipLink />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
